### ISSUE TITLE
Face Blurring

### ISSUE THREAD

**Issue by towner-10** [Northern-Tornadoes-Project/insights#2]

**Comment by Raminh05** [comment]
### Face blurring nearly ready.
- Its docker container fully builds. ✅ 
- Images are being processed by CUDA successfully ✅ 

#### Couple quirks to iron out:
- Within the compose file, mount a folder where yolov8 deps can be stored (e.g. PyTorch) without having the container re-download it every startup
- Sometimes, the Gunicorn worker times out due to the above behaviour (downloading PyTorch takes a while on slow internet)
- WSL2 caches overly-aggressively resulting in extraordinary memory usage by the container

**Comment by Raminh05** [comment]
***UPDATE***
- PyTorch is now downloaded as part of the docker image build
- Gunicorn no longer times out because of that
- Happy days

****WORK TO DO****
- WSL2 still might be a ~~cookie~~ cache monster
- Handle exceptions better in the image processing code
